version: "3.9"

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: nerosense-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nerosense
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: nerosense-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/app/credentials:/app/credentials  # mount credentials safely
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: nerosense-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  